import type { Metadata } from "next";
import Link from "next/link";
import { PublicNav } from "@/components/shared/public-nav";
import { PublicFooter } from "@/components/shared/public-footer";
import {
  Sparkles,
  LayoutTemplate,
  FileDown,
  History,
  Users,
  ShieldCheck,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Features — How DentiSOP Works for Dental Practices",
  description:
    "See how DentiSOP helps dental practices create structured SOPs for OSHA, HIPAA, and CDC compliance. AI generation, dental templates, PDF/Word export, version history, and team sharing.",
};

const features = [
  {
    icon: Sparkles,
    title: "AI SOP Generation for Dental Workflows",
    description:
      "Describe your dental workflow in plain language — sterilization protocols, patient intake, emergency procedures — and DentiSOP generates a structured, OSHA- and HIPAA-compliant SOP in seconds. No formatting headaches, no blank-page anxiety.",
    link: { href: "/signup", label: "Try it free" },
  },
  {
    icon: LayoutTemplate,
    title: "8 Dental-Specific SOP Templates",
    description:
      "Start from proven templates built for dental practices: infection control, instrument sterilization, radiograph protocols, patient check-in, emergency response, OSHA training, front desk procedures, and new hire onboarding. Customize to fit your office.",
    link: { href: "/templates", label: "Browse templates" },
  },
  {
    icon: FileDown,
    title: "Export to PDF and Word for Compliance Binders",
    description:
      "Download your SOPs as polished PDFs for compliance binders and state board audits, or Word docs for collaborative editing. Clean formatting with headers, revision dates, and approval signatures ready to go.",
    link: { href: "/pricing", label: "See export options" },
  },
  {
    icon: History,
    title: "Version History for Inspection Readiness",
    description:
      "Every edit is tracked automatically. Compare versions side by side, see who changed what, and restore previous versions with a single click. Always ready for OSHA inspections and state board audits.",
    link: { href: "/signup", label: "Get started" },
  },
  {
    icon: Users,
    title: "Team Sharing Across Locations and Roles",
    description:
      "Share SOPs across multiple practice locations with role-based access for dentists, hygienists, dental assistants, and front desk staff. Keep everyone aligned with a single source of truth for how your practice operates.",
    link: { href: "/pricing", label: "View team plans" },
  },
  {
    icon: ShieldCheck,
    title: "Compliance-Ready: OSHA, HIPAA, and CDC Formatted",
    description:
      "SOPs generated by DentiSOP follow structured formats aligned with OSHA, HIPAA, and CDC guidelines for dental practices. Consistent headers, revision tracking, and approval workflows help you stay audit-ready at all times.",
    link: { href: "/features", label: "Learn more" },
  },
];

export default function FeaturesPage() {
  return (
    <div className="flex min-h-screen flex-col bg-white">
      <PublicNav />
      <main className="flex-1">
        <div className="mx-auto max-w-4xl px-6 py-16 sm:py-24">
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
            Everything your dental practice needs to create, manage, and share
            SOPs
          </h1>
          <p className="mt-4 text-lg text-gray-600">
            DentiSOP combines AI generation with dental-specific tools so your
            practice can document clinical workflows, meet compliance
            requirements, and keep procedures up to date.
          </p>

          <div className="mt-16 space-y-16">
            {features.map((feature) => (
              <div key={feature.title} className="group">
                <div className="flex items-start gap-4">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-blue-50 text-blue-600">
                    <feature.icon className="h-5 w-5" />
                  </div>
                  <div>
                    <h2 className="text-xl font-semibold text-gray-900">
                      {feature.title}
                    </h2>
                    <p className="mt-2 text-gray-600">{feature.description}</p>
                    <Link
                      href={feature.link.href}
                      className="mt-3 inline-block text-sm font-medium text-blue-600 hover:text-blue-700"
                    >
                      {feature.link.label} &rarr;
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-20 rounded-xl border bg-gray-50 p-8 text-center">
            <h2 className="text-2xl font-bold text-gray-900">
              Ready to streamline your dental practice documentation?
            </h2>
            <p className="mt-2 text-gray-600">
              Start generating professional dental SOPs in minutes.
            </p>
            <Link
              href="/signup"
              className="mt-6 inline-block rounded-lg bg-blue-600 px-6 py-3 text-sm font-semibold text-white hover:bg-blue-700"
            >
              Start generating SOPs
            </Link>
          </div>
        </div>
      </main>
      <PublicFooter />
    </div>
  );
}
