import Link from "next/link";
import {
  Heart,
  Code,
  Factory,
  Landmark,
  ShoppingCart,
  FileText,
  Sparkles,
  Download,
  LayoutTemplate,
  FileDown,
  GitBranch,
  Users,
  ShieldCheck,
  Check,
  Star,
  ArrowRight,
  ChevronDown,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { PLANS, type Plan } from "@/types";

const CONTAINER = "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8";

const TEMPLATES = [
  { title: "Employee Onboarding", description: "Streamline new hire orientation with step-by-step procedures for HR teams.", industry: "HR" },
  { title: "Customer Support Escalation", description: "Define clear escalation paths to resolve customer issues faster.", industry: "SaaS" },
  { title: "Inventory Management", description: "Track stock levels, reorder points, and warehouse procedures efficiently.", industry: "Retail" },
  { title: "Software Deployment", description: "Standardize release pipelines from staging to production environments.", industry: "Technology" },
  { title: "Financial Reporting", description: "Ensure accurate and timely financial reports with repeatable processes.", industry: "Finance" },
  { title: "Quality Control", description: "Maintain product standards with inspection checklists and testing protocols.", industry: "Manufacturing" },
  { title: "Data Backup & Recovery", description: "Protect critical data with documented backup schedules and recovery steps.", industry: "IT" },
  { title: "Incident Response", description: "Respond to security incidents quickly with a structured action plan.", industry: "Security" },
];

const TESTIMONIALS = [
  { quote: "SOPGenius cut our documentation time by 80%. What used to take a full day now takes minutes.", stars: 5, name: "Sarah Chen", role: "Operations Director", company: "MedFlow Health" },
  { quote: "We onboarded 50 new team members last quarter using SOPs generated by this tool. Absolute game-changer.", stars: 5, name: "Marcus Williams", role: "VP of Engineering", company: "ScaleStack" },
  { quote: "The compliance-ready templates saved us weeks of prep before our ISO audit. Highly recommended.", stars: 5, name: "Elena Rodriguez", role: "Quality Manager", company: "PrecisionMfg" },
];

const FAQS = [
  { q: "What is an SOP?", a: "A Standard Operating Procedure (SOP) is a set of step-by-step instructions that help workers carry out routine operations consistently and efficiently. SOPs ensure quality, compliance, and repeatability across your organization." },
  { q: "How does the AI generate SOPs?", a: "SOPGenius uses advanced AI models trained on thousands of real-world SOPs. You describe your process in plain language, and our AI structures it into a professional SOP document complete with roles, steps, quality checks, and compliance notes." },
  { q: "Can I customize the generated SOPs?", a: "Absolutely. Every generated SOP is fully editable. You can modify steps, add roles, adjust formatting, and tailor the document to your exact needs before exporting." },
  { q: "What export formats are supported?", a: "SOPGenius supports PDF, Microsoft Word (.docx), Markdown, and HTML export formats. Pro and Business plans also include custom-branded exports with your company logo." },
  { q: "Is my data secure?", a: "Yes. All data is encrypted in transit and at rest. We use industry-standard security practices and never share your data with third parties. Business plans include SOC 2 compliance and SSO integration." },
  { q: "Can I use this for compliance documentation?", a: "Yes. SOPGenius generates SOPs that align with common compliance frameworks including ISO 9001, ISO 27001, HIPAA, GDPR, SOX, and FDA regulations. Business plans include dedicated compliance tracking features." },
];

const FOOTER_LINKS = {
  Product: [
    { label: "Features", href: "#features" },
    { label: "Templates", href: "#templates" },
    { label: "Pricing", href: "#pricing" },
    { label: "Changelog", href: "#" },
  ],
  Resources: [
    { label: "Blog", href: "#" },
    { label: "Guides", href: "#" },
    { label: "API Docs", href: "#" },
    { label: "Help Center", href: "#" },
  ],
  Company: [
    { label: "About", href: "#" },
    { label: "Careers", href: "#" },
    { label: "Contact", href: "#" },
    { label: "Press", href: "#" },
  ],
  Legal: [
    { label: "Privacy", href: "#" },
    { label: "Terms", href: "#" },
    { label: "Security", href: "#" },
  ],
};

export default function LandingPage() {
  const planKeys = Object.keys(PLANS) as Plan[];

  return (
    <div className="min-h-screen bg-white text-foreground">
      {/* Navigation */}
      <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b">
        <div className={`${CONTAINER} flex items-center justify-between h-16`}>
          <Link href="/" className="text-xl font-bold tracking-tight text-primary">
            SOPGenius
          </Link>

          <div className="hidden md:flex items-center gap-6 text-sm font-medium">
            <a href="#features" className="hover:text-primary transition-colors">Features</a>
            <a href="#templates" className="hover:text-primary transition-colors">Templates</a>
            <a href="#pricing" className="hover:text-primary transition-colors">Pricing</a>
          </div>

          <div className="flex items-center gap-3">
            <Button variant="outline" size="sm" asChild>
              <Link href="/login">Login</Link>
            </Button>
            <Button size="sm" asChild>
              <Link href="/signup">Get Started Free</Link>
            </Button>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="py-20 lg:py-28 bg-gradient-to-b from-slate-50 to-white">
        <div className={`${CONTAINER} grid lg:grid-cols-2 gap-12 items-center`}>
          <div className="space-y-8">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold leading-tight tracking-tight">
              Generate Professional SOPs in{" "}
              <span className="text-primary">60 Seconds</span> with AI
            </h1>
            <p className="text-lg text-muted-foreground max-w-lg">
              Stop spending hours writing standard operating procedures. Describe your process, and
              SOPGenius creates detailed, compliant SOPs instantly.
            </p>
            <div className="flex flex-wrap gap-4">
              <Button size="lg" asChild>
                <Link href="/signup">
                  Generate Your First SOP Free <ArrowRight className="ml-1 h-5 w-5" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" asChild>
                <a href="#how-it-works">See How It Works</a>
              </Button>
            </div>
          </div>

          {/* Decorative mockup */}
          <div className="relative hidden lg:block">
            <div className="rounded-2xl bg-gradient-to-br from-primary/10 via-primary/5 to-transparent border p-8 shadow-xl">
              <div className="space-y-3 mb-6">
                <div className="text-xs font-semibold uppercase tracking-wider text-primary">Input</div>
                <div className="rounded-lg bg-white border p-4 text-sm text-muted-foreground leading-relaxed">
                  &ldquo;When a new employee joins, HR sends a welcome email, assigns a buddy, schedules
                  orientation sessions, and sets up system access...&rdquo;
                </div>
              </div>
              <div className="flex items-center justify-center py-3">
                <Sparkles className="h-6 w-6 text-primary animate-pulse" />
              </div>
              <div className="space-y-3">
                <div className="text-xs font-semibold uppercase tracking-wider text-primary">Generated SOP</div>
                <div className="rounded-lg bg-white border p-4 space-y-2">
                  <div className="h-3 rounded bg-primary/20 w-3/4" />
                  <div className="h-2 rounded bg-slate-100 w-full" />
                  <div className="h-2 rounded bg-slate-100 w-5/6" />
                  <div className="h-2 rounded bg-slate-100 w-full" />
                  <div className="h-2 rounded bg-slate-100 w-4/6" />
                  <div className="mt-3 h-3 rounded bg-primary/15 w-2/4" />
                  <div className="h-2 rounded bg-slate-100 w-full" />
                  <div className="h-2 rounded bg-slate-100 w-5/6" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Social Proof Bar */}
      <section className="py-12 border-y bg-white">
        <div className={`${CONTAINER} text-center space-y-6`}>
          <p className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
            Trusted by 2,000+ businesses
          </p>
          <div className="flex flex-wrap items-center justify-center gap-8 sm:gap-12 text-muted-foreground">
            {[
              { icon: Heart, label: "Healthcare" },
              { icon: Code, label: "SaaS" },
              { icon: Factory, label: "Manufacturing" },
              { icon: Landmark, label: "Finance" },
              { icon: ShoppingCart, label: "Retail" },
            ].map(({ icon: Icon, label }) => (
              <div key={label} className="flex items-center gap-2">
                <Icon className="h-5 w-5" />
                <span className="text-sm font-medium">{label}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="py-20 bg-slate-50">
        <div className={`${CONTAINER} space-y-12`}>
          <div className="text-center space-y-3">
            <h2 className="text-3xl sm:text-4xl font-bold">How It Works</h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Three simple steps to go from process description to professional SOP.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {[
              { step: 1, icon: FileText, title: "Describe Your Process", desc: "Write a plain-language description of the process you want to document. Include as much or as little detail as you like." },
              { step: 2, icon: Sparkles, title: "AI Generates Your SOP", desc: "Our AI analyzes your description and produces a structured SOP with roles, steps, quality checks, and compliance notes." },
              { step: 3, icon: Download, title: "Export & Share", desc: "Download your SOP as PDF, Word, or Markdown. Share with your team or integrate into your document management system." },
            ].map(({ step, icon: Icon, title, desc }) => (
              <Card key={step} className="text-center relative pt-10">
                <div className="absolute -top-5 left-1/2 -translate-x-1/2 h-10 w-10 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold text-sm shadow">
                  {step}
                </div>
                <CardHeader className="items-center gap-2 pb-2">
                  <Icon className="h-8 w-8 text-primary" />
                  <h3 className="text-lg font-semibold">{title}</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">{desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Feature Grid */}
      <section id="features" className="py-20 bg-white">
        <div className={`${CONTAINER} space-y-12`}>
          <div className="text-center space-y-3">
            <h2 className="text-3xl sm:text-4xl font-bold">Everything You Need to Create Better SOPs</h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Powerful features designed to make SOP creation fast, collaborative, and compliant.
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {[
              { icon: Sparkles, title: "AI-Powered Generation", desc: "Transform plain-language descriptions into structured, professional SOPs in seconds using advanced AI models." },
              { icon: LayoutTemplate, title: "Industry Templates", desc: "Start from 50+ pre-built templates tailored for healthcare, manufacturing, finance, and more." },
              { icon: FileDown, title: "Multiple Export Formats", desc: "Export your SOPs to PDF, Word, Markdown, or HTML with custom branding and formatting options." },
              { icon: GitBranch, title: "Version Control", desc: "Track every change with full revision history. Compare versions and roll back when needed." },
              { icon: Users, title: "Team Collaboration", desc: "Invite team members to review, edit, and approve SOPs with role-based access controls." },
              { icon: ShieldCheck, title: "Compliance Ready", desc: "Generate SOPs aligned with ISO 9001, HIPAA, GDPR, SOX, and other regulatory frameworks." },
            ].map(({ icon: Icon, title, desc }) => (
              <Card key={title} className="hover:shadow-lg transition-shadow">
                <CardHeader className="gap-3 pb-2">
                  <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center">
                    <Icon className="h-5 w-5 text-primary" />
                  </div>
                  <h3 className="text-lg font-semibold">{title}</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">{desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Template Showcase */}
      <section id="templates" className="py-20 bg-slate-50">
        <div className={`${CONTAINER} space-y-12`}>
          <div className="text-center space-y-3">
            <h2 className="text-3xl sm:text-4xl font-bold">Popular SOP Templates</h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Jump-start your documentation with ready-made templates for common business processes.
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {TEMPLATES.map((t) => (
              <Card key={t.title} className="hover:shadow-lg transition-shadow group">
                <CardHeader className="pb-2 gap-2">
                  <Badge variant="secondary" className="w-fit text-xs">{t.industry}</Badge>
                  <h3 className="font-semibold">{t.title}</h3>
                </CardHeader>
                <CardContent className="space-y-3">
                  <p className="text-sm text-muted-foreground">{t.description}</p>
                  <Link
                    href="/dashboard/create"
                    className="inline-flex items-center text-sm font-medium text-primary hover:underline"
                  >
                    Use Template <ArrowRight className="ml-1 h-4 w-4 group-hover:translate-x-0.5 transition-transform" />
                  </Link>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-20 bg-white">
        <div className={`${CONTAINER} space-y-12`}>
          <div className="text-center space-y-3">
            <h2 className="text-3xl sm:text-4xl font-bold">Simple, Transparent Pricing</h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Start free, upgrade when you need more. No hidden fees.
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {planKeys.map((key) => {
              const plan = PLANS[key];
              const isPopular = plan.highlighted;
              return (
                <Card
                  key={key}
                  className={`relative flex flex-col ${isPopular ? "ring-2 ring-primary shadow-xl" : ""}`}
                >
                  {isPopular && (
                    <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                      <Badge>Most Popular</Badge>
                    </div>
                  )}
                  <CardHeader className="gap-1 pb-2">
                    <h3 className="text-lg font-bold">{plan.name}</h3>
                    <p className="text-sm text-muted-foreground">{plan.description}</p>
                    <div className="pt-2">
                      <span className="text-4xl font-extrabold">${plan.price}</span>
                      <span className="text-muted-foreground text-sm">/mo</span>
                    </div>
                  </CardHeader>
                  <CardContent className="flex flex-col flex-1 gap-4">
                    <ul className="space-y-2 flex-1">
                      {plan.features.map((f) => (
                        <li key={f} className="flex items-start gap-2 text-sm">
                          <Check className="h-4 w-4 text-primary mt-0.5 shrink-0" />
                          <span>{f}</span>
                        </li>
                      ))}
                    </ul>
                    <Button
                      variant={isPopular ? "default" : "outline"}
                      className="w-full"
                      asChild
                    >
                      <Link href="/signup">
                        {plan.price === 0 ? "Get Started Free" : `Choose ${plan.name}`}
                      </Link>
                    </Button>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 bg-slate-50">
        <div className={`${CONTAINER} space-y-12`}>
          <div className="text-center space-y-3">
            <h2 className="text-3xl sm:text-4xl font-bold">What Our Users Say</h2>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {TESTIMONIALS.map((t) => (
              <Card key={t.name} className="hover:shadow-lg transition-shadow">
                <CardContent className="pt-6 space-y-4">
                  <div className="flex gap-0.5">
                    {Array.from({ length: t.stars }).map((_, i) => (
                      <Star key={i} className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                    ))}
                  </div>
                  <p className="text-sm leading-relaxed text-muted-foreground italic">
                    &ldquo;{t.quote}&rdquo;
                  </p>
                  <div>
                    <p className="font-semibold text-sm">{t.name}</p>
                    <p className="text-xs text-muted-foreground">
                      {t.role}, {t.company}
                    </p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 bg-white">
        <div className={`${CONTAINER} max-w-3xl space-y-10`}>
          <div className="text-center space-y-3">
            <h2 className="text-3xl sm:text-4xl font-bold">Frequently Asked Questions</h2>
          </div>

          <div className="divide-y">
            {FAQS.map(({ q, a }) => (
              <details key={q} className="group py-4">
                <summary className="flex cursor-pointer items-center justify-between font-medium text-sm list-none">
                  {q}
                  <ChevronDown className="h-4 w-4 text-muted-foreground transition-transform group-open:rotate-180" />
                </summary>
                <p className="mt-3 text-sm text-muted-foreground leading-relaxed">{a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 bg-primary text-primary-foreground">
        <div className={`${CONTAINER} text-center space-y-8`}>
          <h2 className="text-3xl sm:text-4xl font-bold max-w-2xl mx-auto">
            Ready to Transform How Your Team Creates SOPs?
          </h2>
          <Button size="lg" variant="secondary" asChild>
            <Link href="/signup">Start Free — No Credit Card Required</Link>
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-16 bg-slate-900 text-slate-300">
        <div className={CONTAINER}>
          <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-10">
            <div className="lg:col-span-1 space-y-3">
              <Link href="/" className="text-xl font-bold text-white">SOPGenius</Link>
              <p className="text-sm text-slate-400">
                AI-powered SOP generation for modern teams.
              </p>
            </div>

            {Object.entries(FOOTER_LINKS).map(([heading, links]) => (
              <div key={heading} className="space-y-3">
                <h4 className="text-sm font-semibold text-white">{heading}</h4>
                <ul className="space-y-2">
                  {links.map((l) => (
                    <li key={l.label}>
                      <a href={l.href} className="text-sm hover:text-white transition-colors">
                        {l.label}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div className="mt-12 pt-8 border-t border-slate-800 text-center text-sm text-slate-500">
            &copy; {new Date().getFullYear()} SOPGenius. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
}
